conf/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'tavern'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tavern.urls')),
]

tavern/urls.py
from django.urls import path

from . import views

app_name = 'tavern'

urlpatterns = [
    #this is going to be the path for my home page
    path('', views.HomeView.as_view(), name='home'),

    #this route has value capturing so it will grab the lunch poll id as the pk var
    #example: localhost:8000/5/ <-- the # 5 is saved to a variable pk that we
    #can use in the view.
    path('<int:pk>/', views.LunchDetailView.as_view(), name='detail'),

    #This route includes value capturing to grab the contest id as the pk var
    path('<int:pk>/results/', views.LunchResultsView.as_view(), name='results'),

    #so does this one
    path('<int:pk>/vote/', views.LunchVoteView.as_view(), name='vote'),
]

tavern/models.py
from django.db import models
from django.utils import timezone

class Lunch(models.Model):
    nickname = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nickname


class Location(models.Model):
    lunch = models.ForeignKey(Lunch, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, default='generic')
    description = models.TextField(default=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.title

tavern/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, View
from django.utils import timezone

from .models import Location, Lunch


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        """
        Return the last five published contests (not including those set to be
        published in the future).
        """
        lunches = Lunch.objects.filter(
            date__lte=timezone.now()
        ).order_by('date')[:5]

        context = {
            'latest_lunches': lunches
        }

        return context


class LunchDetailView(TemplateView):
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        available_options = Location.objects.all()
        # The contest primary key is included on the url: localhost:8000/5/
        # We use value capturing in our urls.py to get the # 5 and save it to pk
        # The pk variable is in the dictionary self.kwargs, and we can use .get() on
        # the self.kwargs dict.
        vote_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        vote = Lunch.objects.get(pk=vote_pk)

        # Create a context dictionary that will be sent to our template
        context = {
            'details': available_options,
            'vote': vote,
        }

        # Our get_context_data() function always expects us to return a context dict
        return context


class LunchResultsView(TemplateView):
    template_name = 'results.html'

    def get_context_data(self, **kwargs):
        # The contest primary key is included on the url: locahost:8000/5/results/
        # We use value capturing in our urls.py to get the # 5 and save it to pk
        # The pk variable is in the dictionary self.kwargs, and we can use .get() on
        # the self.kwargs dict.
        vote_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        vote = Lunch.objects.get(pk=vote_pk)

        # Create a context dictionary that will be sent to our template
        context = {
            'vote': vote
        }

        # Our get_context_data() function always expects us to return a context dict
        return context


# This view will not be a template view since we won't actually show a screen.
# Once a user submits to this screen we will redirect.
class LunchVoteView(View):

    # We are going to receive a POST request with this view, so we're going to create a method called post.
    def post(self, request, **kwargs):
        # The contest primary key is included on the url: locahost:8000/5/vote/
        # We use value capturing in our urls.py to get the # 5 and save it to pk
        # The pk variable is in the dictionary self.kwargs, and we can use .get() on
        # the self.kwargs dict.
        vote_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        vote = Lunch.objects.get(pk=vote_pk)

        # The user selected a picture that they wanted to vote for in the contest.
        # They selected one of the radio buttons: <input name="photo" value="2" .../>
        # When they submitted the form, the name of the input got sent to the server with the value in the input.
        # We can use the input name get the value from the POST dictionary.
        lunch_spot_voted_for_id = self.request.POST.get('location')

        # Now we want to take our contest and lookup the photo object that the user selected
        selected_lunch_spot = vote.location_set.get(pk=lunch_spot_voted_for_id)

        selected_lunch_spot.votes += 1
        selected_lunch_spot.save()

        # Now get the URL for our results screen using the route name from urls.py
        results_url = reverse('tavern:results', args=(vote.pk,))

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(results_url)

tavern/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display|Open+Sans+Condensed:300" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/styles.css">
</head>
<body>
<header>
    <h1>Tavern</h1>
</header>
<div>
    <h5 class="blue"><a href="/admin">Create A Poll</a></h5>
</div>
<div class="container">
<div class="background">

{% block content %}{% endblock %}

</div>
</div>
<script type="text/javascript" src="../static/main.js"></script>
</body>
</html>

tavern/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <form class="center" action="{% url 'tavern:vote' vote.id %}" method="post">
        {% csrf_token %}
        {% for location in vote.location_set.all %}
        <label for="Location{{ forloop.counter }}">
            <h4 class="col">{{ location.title }}</h4>
        </label>

<div class="center col">
        Select: <input type="radio" name="location" id="location{{ forloop.counter }}" value="{{ location.id }}">
    {% endfor %}
</div>
<div>
    </form>
        <input type="submit" class="btn btn-primary" value="Vote">




</div>
{% endblock %}

tavern/templates/home.html
{% extends 'base.html' %}


{% block content %}
    <h6>Welcome to Tavern</h6>
    {% if latest_lunches %}
        <ul class="list-group">
            {# Loop over the latest_contests list and get each contest #}
            {% for lunch in latest_lunches %}
                {# We can build a url with the name of our path using the url template tag #}
                <li class="center link-adjust"><a href="{% url 'tavern:detail' lunch.id %}">{{ lunch.nickname }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="center">No lunch polls. Get some friends.</p>
    {% endif %}
{% endblock %}

tavern/templates/results.html
{% extends 'base.html' %}

{% block content %}
<ul class="center">
    {% for location in vote.location_set.all %}
        <li> {{ location.title }} -- {{ location.votes }} vote{{ location.votes|pluralize }}</li>
    {% endfor %}
</ul>
    <div class="center">
    <a href="{% url 'tavern:detail' vote.id %}">Vote again?</a>
    </div>
{% endblock %}